/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountLogin: typeof import('./src/views/login/AccountLogin.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/views/user/Header.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Index: typeof import('./src/views/Index.vue')['default']
    Login: typeof import('./src/views/login/Login.vue')['default']
    PhoneLogin: typeof import('./src/views/login/PhoneLogin.vue')['default']
    Profile: typeof import('./src/views/user/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/views/user/Setting.vue')['default']
    Welcome: typeof import('./src/views/Welcome.vue')['default']
  }
}
