/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountLogin: typeof import('./src/views/entrance/components/AccountLogin.vue')['default']
    AccountRegister: typeof import('./src/views/entrance/components/AccountRegister.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Diagraming: typeof import('./src/views/diagraming/Diagraming.vue')['default']
    Diagrams: typeof import('./src/views/home/Diagrams.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmailLogin: typeof import('./src/views/entrance/components/EmailLogin.vue')['default']
    EmailRegister: typeof import('./src/views/entrance/components/EmailRegister.vue')['default']
    Entrance: typeof import('./src/views/entrance/Entrance.vue')['default']
    File: typeof import('./src/views/home/components/File.vue')['default']
    FindAccount: typeof import('./src/views/entrance/components/FindAccount.vue')['default']
    FindAccountResetPassword: typeof import('./src/views/entrance/components/FindAccountResetPassword.vue')['default']
    FindAccountVerifyCode: typeof import('./src/views/entrance/components/FindAccountVerifyCode.vue')['default']
    Folder: typeof import('./src/views/home/components/Folder.vue')['default']
    Header: typeof import('./src/views/home/components/Header.vue')['default']
    History: typeof import('./src/views/home/History.vue')['default']
    Home: typeof import('./src/views/home/Home.vue')['default']
    Login: typeof import('./src/views/entrance/components/Login.vue')['default']
    Menu: typeof import('./src/views/home/components/Menu.vue')['default']
    Profile: typeof import('./src/views/user/Profile.vue')['default']
    Recommend: typeof import('./src/views/user/Recommend.vue')['default']
    Register: typeof import('./src/views/entrance/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/views/user/Setting.vue')['default']
    Shares: typeof import('./src/views/home/Shares.vue')['default']
    Stars: typeof import('./src/views/home/Stars.vue')['default']
    Templates: typeof import('./src/views/user/Templates.vue')['default']
    Welcome: typeof import('./src/views/Welcome.vue')['default']
  }
}
